name = "Pirate Pals"
love_version = "11.4"
default_targets = ["win64", "macos"]
build_directory = "build"
love_files = [
    "+main.lua",
    "+conf.lua",
    "+src/**",
]

[windows]
exe_metadata = { FileDescription = "Pirate Pals", ProductName = "Pirate Pals" }

[appimage]
artifacts = "appimage"
